### ISSUE TITLE
file encoding errors

### ISSUE THREAD

**Issue by kevinpohlmeier** [TotalALM/VSTS-Tasks#17]
My files are encoded in UTF 16 LE. When running tokenizer, I get the below error. The problem is that the valid values of Set-Content do not match up with the outputs of you Get-FileEncoding.

https://technet.microsoft.com/en-us/library/hh847827.aspx

It looks like the Get-FileEncoding is the same as the following gist, which uses Out-File instead of Set-Content. 
https://gist.github.com/jpoehls/2406504

##[error]Cannot bind parameter 'Encoding'. Cannot convert value "Unicode UTF-16 Little-Endian" to type "Microsoft.PowerShell.Commands.FileSystemCmdletProviderEncoding". Error: "Unable to match the identifier name Unicode UTF-16 Little-Endian to a valid enumerator name.  Specify one of the following enumerator names and try again: Unknown, String, Unicode, Byte, BigEndianUnicode, UTF8, UTF7, UTF32, Ascii, Default, Oem"

**Comment by pcoombe** [comment]
My files are encoded UTF8, but because they have no BOM, they are being treated as ASCII.
This ends up corrupting the file as anything non ascii gets replaced with ??

**Comment by KevinDMack** [comment]
Thanks so much for reporting this, we are investigating this further and will be including an update in the next release.

**Comment by mrmorphic** [comment]
Any ETA on this? This is nearly 6 months old. This will block many projects.

**Comment by rohrerb** [comment]
Would be happy to investigate this for you.  Can you share a file with us that you are running into issue with?

**Comment by mrmorphic** [comment]
I can't provide the file we're using, but it is very easy to create a test file. The input can be an HTML file with non-ascii characters.

**Comment by rohrerb** [comment]
So your doing tokenization on html files?  If so, we certainly didn’t test this. 😃

I will start looking at it tomorrow.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mrmorphic** [comment]
The tokenisation we're doing is on javascript rather than HTML, but it would be the same either way.

**Comment by rohrerb** [comment]
Resolved with the following commit.  https://github.com/TotalALM/VSTS-Tasks/commit/3a1eda4c6a653db538a0c85830e29d517c5e4a06

I will package this task and publish on the marketplace by EOD.

**Comment by mrmorphic** [comment]
Hi. Thanks for your responsiveness :-)  I'll hope to test it in a week or so.

**Comment by mrmorphic** [comment]
Hi there. We finally got around to testing, and still experienced the problem. I'm not sure how to know if/when updates to the tool in marketplace actually take place.

Anyway, to give you an explicit example of the problem, here are two snippets that came from the deployed server, one without the tokenizer and one with. These files are in main.bundle.js, the output of web pack. As such, it's javascript with HTML embedded. If you look in the first <h1>, there is a letter with a macron, which appears as ??  in the second sample.

Cheers
M


Without tokenizer:
module.exports = "<div class=\"container\">\r\n    <div class=\"row\">\r\n        <div class=\"col-sm-12\">\r\n            <h1>Your details<br><span lang=\"mi\">Ō taipitopito</span></h1>\r\n            \r\n            <form [formGroup]=\"formGroup\">\r\n\r\n                <div>\r\n\r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('applicantTitle')\"></dia-radio-group>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('firstAndMiddleName')\"></dia-textfield>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('surname')\"></dia-textfield>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('firstAndMiddleNameAtBirth')\"></dia-textfield>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('surnameAtBirth')\"></dia-textfield>\r\n\r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('gender')\"></dia-radio-group>\r\n\r\n                    <dia-datepicker [formGroup]=\"formGroup\" [fieldDef]=\"field('dateOfBirth')\"></dia-datepicker>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('placeOfBirth')\"></dia-textfield>\r\n\r\n                    <div class=\"form-group\">\r\n                        <label>What is your usual residential address?<span class='asterisk'>*</span></label>\r\n                        <p id=\"helpResidentialAddress\">We need the address where you live, not your postal address. If your address doesn't appear when you start typing, enter it manually.</p>\r\n                    </div>\r\n\r\n                    <dia-address [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialStreetAddress')\" (newAddress)=\"onNewAddress($event)\"></dia-address>\r\n                    \r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialSuburb')\"></dia-textfield>\r\n                    \r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialCity')\"></dia-textfield>\r\n                    \r\n                    <dia-country [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialCountry')\"></dia-country>\r\n                    \r\n                    <br>\r\n                    \r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('previousRelationshipStatus')\"></dia-radio-group>\r\n\r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('previousRelationshipEnd')\"></dia-radio-group>\r\n\r\n                    <dia-datepicker [formGroup]=\"formGroup\" [fieldDef]=\"field('previousRelationshipEndDate')\"></dia-datepicker>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('occupation')\"></dia-textfield>\r\n\r\n                </div>\r\n            </form>\r\n        </div>\r\n    </div>"



With tokenizer:
module.exports = "<div class=\"container\">\r\n    <div class=\"row\">\r\n        <div class=\"col-sm-12\">\r\n            <h1>Your details<br><span lang=\"mi\">?? taipitopito</span></h1>\r\n            \r\n            <form [formGroup]=\"formGroup\">\r\n\r\n                <div>\r\n\r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('applicantTitle')\"></dia-radio-group>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('firstAndMiddleName')\"></dia-textfield>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('surname')\"></dia-textfield>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('firstAndMiddleNameAtBirth')\"></dia-textfield>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('surnameAtBirth')\"></dia-textfield>\r\n\r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('gender')\"></dia-radio-group>\r\n\r\n                    <dia-datepicker [formGroup]=\"formGroup\" [fieldDef]=\"field('dateOfBirth')\"></dia-datepicker>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('placeOfBirth')\"></dia-textfield>\r\n\r\n                    <div class=\"form-group\">\r\n                        <label>What is your usual residential address?<span class='asterisk'>*</span></label>\r\n                        <p id=\"helpResidentialAddress\">We need the address where you live, not your postal address. If your address doesn't appear when you start typing, enter it manually.</p>\r\n                    </div>\r\n\r\n                    <dia-address [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialStreetAddress')\" (newAddress)=\"onNewAddress($event)\"></dia-address>\r\n                    \r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialSuburb')\"></dia-textfield>\r\n                    \r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialCity')\"></dia-textfield>\r\n                    \r\n                    <dia-country [formGroup]=\"formGroup\" [fieldDef]=\"field('residentialCountry')\"></dia-country>\r\n                    \r\n                    <br>\r\n                    \r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('previousRelationshipStatus')\"></dia-radio-group>\r\n\r\n                    <dia-radio-group [formGroup]=\"formGroup\" [fieldDef]=\"field('previousRelationshipEnd')\"></dia-radio-group>\r\n\r\n                    <dia-datepicker [formGroup]=\"formGroup\" [fieldDef]=\"field('previousRelationshipEndDate')\"></dia-datepicker>\r\n\r\n                    <dia-textfield [formGroup]=\"formGroup\" [fieldDef]=\"field('occupation')\"></dia-textfield>\r\n\r\n                </div>\r\n            </form>\r\n        </div>\r\n    </div>"

**Comment by pcoombe** [comment]
@mrmorphic this was my original use case, bundled js file.
i ended up swapping to https://github.com/colindembovsky/cols-agent-tasks/tree/master/Tasks/ReplaceTokens

**Comment by mrmorphic** [comment]
@pcoombe cheers for that, will try that too.

**Comment by kevinpohlmeier** [comment]
Changing from Set-Content to Out-File did not solve this problem. The list of valid values for the Encoding parameter of Out-File is: "unknown, string, unicode, bigendianunicode, utf8, utf7, utf32, ascii, default, oem".

Not all of the return values of your Get-FileEncoding function return a value in that list of valid values. For example, it can return "Unicode UTF-16 Little-Endian". I had to change that one to simply "Unicode" to get the task to work for me.

Please update the Get-FileEncoding method to only return valid values for the Encoding parameter of Out-File.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file?view=powershell-6
