### ISSUE TITLE
$_Trim() problem

### ISSUE THREAD

**Issue by ranjan-ranjan** [TotalALM/VSTS-Tasks#7]
There is some problem created in line 83 here: https://github.com/TotalALM/VSTS-Tasks/blob/master/Tasks/Code%20Analysis/task/codeanalysis.ps1

**Comment by mkokabi** [comment]
Is anyone working on fixing this issue. I am getting the same error:
`$chkdll = CheckFileDirectory -path $buildDirectory.Trim()\$_.Trim()`

**Comment by ranjan-ranjan** [comment]
you don't have to give \$_.Trim()
it will work
the forked repository i have is much better

**Comment by mkokabi** [comment]
Hi Ranjan,I am not giving \$_.Trim(). I just found it in the logs. Do you mean I should change the powershell and take that out.RegardsMohsen 

    On Saturday, 9 July 2016, 0:02, ranjan-ranjan <notifications@github.com> wrote:
 

 you don't have to give \$_.Trim()
it will work
the forked repository i have is much better—

**Comment by ranjan-ranjan** [comment]
giving just `$chkdll = CheckFileDirectory -path $buildDirectory.Trim()` will solve the problem.

**Comment by MangeshBorolkar** [comment]
I am also facing the same issue. Can this issue be fixed at source?

**Comment by rohrerb** [comment]
This issue has been resolved.  I apologize it has taken so long, we were not able to reproduce the issue.  A new package has been published to the marketplace that includes this change. https://marketplace.visualstudio.com/items?itemName=TotalALM.totalalm-codeanalysis

**Comment by ranjan-ranjan** [comment]
when was this first published?

**Comment by mkokabi** [comment]
Hi,
We got the latest version and deployed but still get the problem:
Logs
2016-07-13T23:45:10.0931079Z Executing the powershell script: D:\TFS Build vNext\vNextAgent1\tasks\CodeAnalysis\1.12.0\codeanalysis.ps1
 
2016-07-13T23:45:10.2962455Z Starting Code Analysis
 
2016-07-13T23:45:12.4507788Z Include file: D:\TFS Build vNext\vNextAgent1\_work\6\a.Trim()\EF.dll.Trim()
 
2016-07-13T23:45:12.4507788Z Include file: D:\TFS Build vNext\vNextAgent1\_work\6\a.Trim()\CommonLibrary.dll.Trim()

07-13T23:45:13.7585974Z Rule set found at 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\Rule Sets\BasicCorrectnessRules.ruleset'
 
2016-07-13T23:45:13.8679251Z ##[error]* Could not load file: 'D:\TFS Build vNext\vNextAgent1\_work\6\a.Trim()\EF.dll.Trim() '.
 
2016-07-13T23:45:13.8679251Z ##[error]* Could not load file: 'D:\TFS Build vNext\vNextAgent1\_work\6\a.Trim()\CommonLibrary.dll.Trim() '.

If it helps we are on TFS 2015.U2 and agent service is version 1.95.0
